### ISSUE TITLE
Kube-ui Installation Problem

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kube-ui#10]
```
[06:57:54] Using gulpfile /kube-ui/master/gulpfile.js
[06:57:54] Starting 'sync group6:0'...
[06:57:54] Starting 'clean'...
[06:57:54] Finished 'clean' after 28 ms
[06:57:54] Finished 'sync group6:0' after 30 ms
[06:57:54] Starting 'sync group6:1'...
[06:57:54] Starting 'sync group7:0'...
[06:57:54] Starting 'copy:shared-assets'...
[06:57:54] Finished 'copy:shared-assets' after 29 ms
[06:57:54] Finished 'sync group7:0' after 29 ms
[06:57:54] Starting 'sync group7:1'...
[06:57:54] Starting 'copy:components'...
[06:57:54] Tested 26 tests, 26 passes, 0 failures: PASS
[06:57:54] Finished 'copy:components' after 84 ms
[06:57:54] Finished 'sync group7:1' after 84 ms
[06:57:54] Starting 'sync group7:2'...
[06:57:54] Starting 'sync group3:0'...
[06:57:54] Starting 'content:html:app'...
[06:57:54] Finished 'content:html:app' after 16 ms
[06:57:54] Finished 'sync group3:0' after 17 ms
[06:57:54] Starting 'sync group3:1'...
[06:57:54] Starting 'content:html:views'...
[06:57:54] Finished 'content:html:views' after 17 ms
[06:57:54] Finished 'sync group3:1' after 18 ms
[06:57:54] Starting 'content:html'...
[06:57:54] Finished 'content:html' after 18 μs
[06:57:54] Finished 'sync group7:2' after 36 ms
[06:57:54] Starting 'sync group7:3'...
[06:57:54] Starting 'sync group1:0'...
[06:57:54] Starting 'scripts:vendor:base'...
[06:57:54] ✗ FAIL: Missing 16 expected files: ../../third_party/ui/bower_components/jquery/dist/jquery.min.js, ../../third_party/ui/bower_components/hammerjs/hammer.js, ../../third_party/ui/bower_components/angular/angular.js, ../../third_party/ui/bower_components/angular-cookies/angular-cookies.js, ../../third_party/ui/bower_components/angular-animate/angular-animate.js, ../../third_party/ui/bower_components/angular-json-human/dist/angular-json-human.js, ../../third_party/ui/bower_components/angular-route/angular-route.js, ../../third_party/ui/bower_components/angular-css/angular-css.js, ../../third_party/ui/bower_components/angular-aria/angular-aria.js, ../../third_party/ui/bower_components/angular-animate/angular-animate.js, ../../third_party/ui/bower_components/angular-material/angular-material.min.js, ../../third_party/ui/bower_components/angular-filter/dist/angular-filter.min.js, ../../third_party/ui/bower_components/ng-lodash/build/ng-lodash.js, ../../third_party/ui/bower_components/string-format-js/format.js, ../../third_party/ui/bower_components/sprintf/dist/sprintf.min.js, ../../third_party/ui/bower_components/jsonpath/lib/jsonpath.js
[06:57:54] Tested 1 tests, 0 passes, 1 failures: FAIL

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-expect-file'
Failed 1 expectations
    at DestroyableTransform.endStream [as _flush] (/kube-ui/master/node_modules/gulp-expect-file/index.js:90:26)
    at DestroyableTransform.<anonymous> (/kube-ui/master/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:92:17)
    at prefinish (/kube-ui/master/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:450:12)
    at finishMaybe (/kube-ui/master/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:458:7)
    at endWritable (/kube-ui/master/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at DestroyableTransform.Writable.end (/kube-ui/master/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DestroyableTransform.onend (/kube-ui/master/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)

npm ERR! kubernetes-ui@0.3.0 poststart: `gulp`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the kubernetes-ui@0.3.0 poststart script.
npm ERR! This is most likely a problem with the kubernetes-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls kubernetes-ui
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-123.20.1.el7.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /kube-ui/master
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /kube-ui/master/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ohohoreilly** [comment]
@kgrvamsi I'll take a look shortly and get back to you.

**Comment by ohohoreilly** [comment]
@kgrvamsi looks like we need to fix the `third_party` includes since moving the a separate repo. I'll work on a fix. Thanks for the bug report.

**Comment by ohohoreilly** [comment]
@kgrvamsi https://github.com/kubernetes/kube-ui/pull/11 fixes the issue that you've reported in https://github.com/kubernetes/kube-ui/issues/10

`[18:06:49] Finished 'build' after 3.19 μs`

**Comment by kgrvamsi** [comment]
Thanks @preillyme  will give it a try today.
